## To use AWS EBS CSI Driver to provision volumes, uncomment the first value
## and configure the parameters below
# aws_ebs_csi_enabled: true
# enableVolumeScheduling: true
# enableVolumeSnapshot: false
# enableVolumeResizing: false
# aws_ebs_csi_controller_replicas: 1
# aws_ebs_csi_driver_image_tag: latest
